
package io.github.pdkst.models.openai.api.chat.response;

import io.github.pdkst.models.openai.api.chat.request.FunctionCall;
import io.github.pdkst.models.openai.api.chat.request.ToolCall;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * 上下文消息
 *
 * @author pdkst
 * @since 2023-07-30
 */
@Data
@NoArgsConstructor
public class ChoiceMessage {
    /**
     * The role of the author of this message.
     */
    private String role;
    /**
     * The contents of the message.
     */
    private String content;
    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    private FunctionCall function_call;
    /**
     * The tool calls generated by the model, such as function calls.
     */
    private List<ToolCall> tool_calls;
}