package io.github.pdkst.models.openai.api.finetuning.request;

import io.github.pdkst.models.annotation.Required;
import lombok.Data;

/**
 * @author pdkst.zhang
 * @since 2024/04/07
 */
@Data
public class WandbSettings {
    /**
     * The name of the project that the new run will be created under.
     */
    @Required
    private String project;
    /**
     * A display name to set for the run. If not set, we will use the Job ID as the name.
     */
    private String name;
    /**
     * The entity to use for the run. This allows you to set the team or username of the WandB user that you would
     * like associated with the run. If not set, the default entity for the registered WandB API key is used.
     */
    private String entity;
    /**
     * A list of tags to be attached to the newly created run. These tags are passed through directly to WandB. Some
     * default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}", "openai/{ftjob-abcdef}".
     */
    private String[] tags;
}
