package io.github.pdkst.models.openai.api.chat.request;

import io.github.pdkst.models.annotation.Required;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author pdkst.zhang
 * @since 2023/10/29
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class FunctionCall {
    /**
     * The arguments to call the function with,
     * as generated by the model in JSON format.
     * Note that the model does not always generate valid JSON,
     * and may hallucinate parameters not defined by your function schema.
     * Validate the arguments in your code before calling your function.
     */
    @Required
    private String arguments;
    /**
     * The name of the function to call.
     */
    @Required
    private String name;
}
