package io.github.pdkst.models.openai.endpoint.chat.response;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 选择项
 *
 * @author pdkst
 * @since 2023-07-30
 */
@NoArgsConstructor
@Data
public class ChunkChoice implements Comparable<ChunkChoice> {
    /**
     * The index of the choice in the list of choices.
     */
    private Integer index;
    /**
     * A chat completion message generated by the model.
     */
    private ChunkChoiceDelta delta;
    /**
     * The reason the model stopped generating tokens.
     * This will be
     * <p>
     * "stop" if the model hit a natural stop point or a provided stop sequence,
     * <p>
     * "length" if the maximum number of tokens specified in the request was reached,
     * <p>
     * "content_filter" if content was omitted due to a flag from our content filters,
     * <p>
     * "tool_calls" if the model called a tool,
     * <p>
     * or "function_call" (deprecated) if the model called a function.
     */
    private String finish_reason;
    /**
     * Log probability information for the choice.
     */
    private LogProb logprobs;

    @Override
    public int compareTo(ChunkChoice o) {
        return Integer.compare(this.getIndex(), o.getIndex());
    }
}